# Лабораторная 2 
## 1.	Использование команд библиотеки NumPy

## 1.1. Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5

In [2]:
import numpy as np
my_array = np.arange(5, 101, 5)
print(my_array)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


## 2.1. Из полученного массива получить массив с кратными 10 числами

In [3]:
my_array_10 = my_array[my_array % 10 == 0]
my_array_10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

## 3.1. Получить двумерный массив с двумя столбцами


In [17]:
my_2d_array = my_array.reshape(10, 2)
my_2d_array

array([[  5,  10],
       [ 15,  20],
       [ 25,  30],
       [ 35,  40],
       [ 45,  50],
       [ 55,  60],
       [ 65,  70],
       [ 75,  80],
       [ 85,  90],
       [ 95, 100]])

## 4.1.Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5

In [20]:
my_second_array = my_array - 5
my_second_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

## 5.1.	Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте .T для транспонирования матрицы.

In [32]:
combined_array = np.hstack((my_2d_array, my_second_array.reshape(10, 2))).T
combined_array

array([[  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95]])

## 6.1. Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы


In [39]:
result = combined_array.copy()
result[1:3, :] = result[1:3, :] / my_array[:2, np.newaxis]
result

array([[ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95]])

## 7.1 Оставить только те значения, которые не изменились после деления


In [41]:
result = result[:, (result[0] == result[1])]
result

array([], shape=(4, 0), dtype=int64)

## 8.1 Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки


In [42]:
result_2d = combined_array.copy()
result_2d[[0, 2]] = result_2d[[2, 0]]
result_2d

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95]])

## 9.1 Получить среднее, медиану и стандартное отклонение для каждой строки


In [43]:
mean_values = np.mean(result_2d, axis=1)
median_values = np.median(result_2d, axis=1)
std_deviation = np.std(result_2d, axis=1)
print(f"Среднее: {mean_values}")
print(f"Медиана: {median_values}")
print(f"Стандартное: {std_deviation}")


Среднее: [45. 55. 50. 50.]
Медиана: [45. 55. 50. 50.]
Стандартное: [28.72281323 28.72281323 28.72281323 28.72281323]


## 10.1 Сделать нормализацию на максимальное значение вдоль строк


In [44]:
normalized_array = result_2d / result_2d.max(axis=1)[:, np.newaxis]
normalized_array

array([[0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.1       , 0.2       , 0.3       , 0.4       , 0.5       ,
        0.6       , 0.7       , 0.8       , 0.9       , 1.        ],
       [0.05263158, 0.15789474, 0.26315789, 0.36842105, 0.47368421,
        0.57894737, 0.68421053, 0.78947368, 0.89473684, 1.        ],
       [0.05263158, 0.15789474, 0.26315789, 0.36842105, 0.47368421,
        0.57894737, 0.68421053, 0.78947368, 0.89473684, 1.        ]])

# 2.	Использование команд библиотеки pandas

## 2.1 Импортируйте данные из файла “Global Population Trends(2016-2022).csv”.


In [45]:
import pandas as pd
df = pd.read_csv("Global Population Trends(2016-2022).csv")

## 2.2 Считайте несколько первых записей таблицы (head())


In [46]:
df.head()

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8         3.0  
2                  46.3         3.0  
3                  44.8         3.0  
4                  43.4         3.0

## 2.3 Определите размерность данного фрейма (shape())


In [47]:
print("Размерность фрейма:", df.shape)

Размерность фрейма: (1073, 12)


## 2.4 Выведите название заголовков столбцов фрейма (columns)


In [48]:
df.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

## 2.5 Получите описание всех переменных (полей) (info())


In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB


## 2.6 Удалите строки, не содержащие значения в столбце «Total Population»


In [50]:
df1 = df[df['Total Population'] != '-']
df1

Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
6                   105            79.0      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -            61.0      34.511       6.973   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
6              1.44                   8.3         0.0  
...             ...                   ...         ...  
1067          4.308                  40.2         3.0  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[864 rows x 12 columns]

## 2.7 Получите описательную статистику по переменным


In [51]:
df1.describe()

Year  Birth Rate  Death Rate
count   864.000000  864.000000  864.000000
mean   2019.500000   18.548384    7.889123
std       1.118682    9.887518    3.041385
min    2018.000000    0.000000    0.000000
25%    2018.750000   10.500000    6.116500
50%    2019.500000   15.628500    7.453500
75%    2020.250000   25.565000    9.385000
max    2021.000000   46.127000   21.700000

## 2.8 Выполните сортировку данных по нескольким критериям (например, по Total Population и Year)


In [52]:
df1 = df1.sort_values(by=['Total Population', 'Year'], ascending=[False, True])
df1

Country  Year Total Population Urban Population Rural Population  \
832   Seychelles  2021           99,258           57,542           41,716   
831   Seychelles  2020           98,462           56,661           41,801   
830   Seychelles  2019           97,625           55,762           41,863   
1047     Vietnam  2021       97,468,029       37,088,534       60,379,495   
829   Seychelles  2018           96,762           54,855           41,907   
...          ...   ...              ...              ...              ...   
302     Eswatini  2018        1,160,428          276,170          884,258   
260     Djibouti  2021        1,105,557          864,734          240,823   
259     Djibouti  2020        1,090,156          850,998          239,158   
258     Djibouti  2019        1,073,994          836,802          237,192   
257     Djibouti  2018        1,057,198          822,257          234,941   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
832                   -            73.0      16.800       9.300   
831                 214            77.0      15.800       6.800   
830                 212            74.0      16.400       8.100   
1047                  -            74.0      15.008       7.317   
829                 210            73.0      17.100       8.400   
...                 ...             ...         ...         ...   
302                  67            59.0      25.718       9.324   
260                   -            62.0      22.205       9.147   
259                  47            63.0      22.477       8.821   
258                  46            63.0      22.748       8.421   
257                  46            63.0      22.982       8.347   

     Fertility Rate Infant Mortality Rate Growth Rate  
832            2.46                  12.0         1.0  
831            2.29                  12.2         1.0  
830            2.36                  12.4         1.0  
1047          1.944                  16.4         1.0  
829            2.41                  12.5         1.0  
...             ...                   ...         ...  
302           2.962                  45.4         1.0  
260           2.804                  45.9         1.0  
259           2.848                  47.2         1.0  
258           2.891                  48.7         2.0  
257           2.929                  50.3         2.0  

[864 rows x 12 columns]

## 2.9 Экспорт фрейма в MS Excel

In [21]:
df1.to_excel("population_trends.xlsx", index=False)